{% set name = "pysurvival" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57cb567323fa314ceaf17fe39745b007855606cb1304a4124a78334ff9d03707

build:
  number: 5
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
    - setuptools
  run:
    - matplotlib-base
    - setuptools
    - pandas
    - progressbar
    - pyarrow
    - python
    - scikit-learn
    - scipy
    - pytorch >=1.7.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pysurvival
    - pysurvival.datasets
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://www.pysurvival.io
  summary: Open source package for Survival Analysis modeling
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sarthakpati
